#!/bin/bash

# Display the current track on Spotify if it's running.
DISPLAY_TRACK=true

i3-get-workspace()
{
  cmd='.nodes[1].nodes[1].nodes[] | '
  cmd=$cmd'.name as $wk | recurse(.nodes[]; has("nodes")) | '
  cmd=$cmd'if (.type != "workspace" and .name and (.name | test("'
  cmd=$cmd"$1"
  cmd=$cmd'"; "i"))) then ($wk) else (. | empty) end'
  i3-msg -t get_tree | jq "$cmd"
}

if [[ $(ps -U root -u root -N | grep -Fo 'spotify') == *spotify* ]]; then
  if [ "$DISPLAY_TRACK" == true ]; then
    TITLE=`playerctl -p spotify metadata 'xesam:title'`
    ARTIST=`playerctl -p spotify metadata 'xesam:artist'`
    ALBUM=`playerctl -p spotify metadata 'xesam:album'`

    # If "title - artist - album" is very long, just display the
    # title and artist.
    NCHAR=$((${#TITLE} + ${#ARTIST} + ${#ALBUM}))
    if [[ $NCHAR -gt 30 || "$ALBUM" == "$TITLE" ]]; then
      TRACK=`echo $TITLE " - " $ARTIST`
      echo "$TRACK" | sed -e 's/?/\?/g'
    else
      TRACK=`echo $TITLE " - " $ARTIST " - " $ALBUM`
      echo "$TRACK" | sed -e 's/?/\?/g'
    fi
  fi

  if [[ $BLOCK_BUTTON == '1' ]]; then
    WK=$(i3-get-workspace "^spotify")
    i3-msg "workspace $WK"
  fi

  if [[ $BLOCK_BUTTON == '3' ]]; then
    TITLE=`playerctl -p spotify metadata 'xesam:title'`
    ARTIST=`playerctl -p spotify metadata 'xesam:artist'`
    ALBUM=`playerctl -p spotify metadata 'xesam:album'`
    notify-send "$TITLE" "$ARTIST\n$ALBUM" \
      -i /usr/share/icons/Numix-Circle/48/apps/spotify.svg
  fi
else
  exit 0
fi
